/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kumar gaurav
 */
public class ppf2 extends javax.swing.JFrame {

    /**
     * Creates new form ppf1
     */
    public ppf2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        MsgDialog = new javax.swing.JDialog();
        okbtn = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        titlab1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        titlab2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wtf = new javax.swing.JTextField();
        acb = new javax.swing.JComboBox();
        cal = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst = new javax.swing.JList();
        ck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        stf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cd = new javax.swing.JButton();
        dlb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ntf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        scpn = new javax.swing.JScrollPane();
        lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        yrb = new javax.swing.JRadioButton();
        nrb = new javax.swing.JRadioButton();

        okbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        okbtn.setForeground(new java.awt.Color(0, 0, 204));
        okbtn.setText("Ok");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        Message.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 0, 51));
        Message.setText("\"Cloth limit is upto 1kg(please enter in decimal degit)\"");

        javax.swing.GroupLayout MsgDialogLayout = new javax.swing.GroupLayout(MsgDialog.getContentPane());
        MsgDialog.getContentPane().setLayout(MsgDialogLayout);
        MsgDialogLayout.setHorizontalGroup(
            MsgDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MsgDialogLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(Message)
                .addGap(62, 62, 62))
            .addGroup(MsgDialogLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(okbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MsgDialogLayout.setVerticalGroup(
            MsgDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MsgDialogLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(Message)
                .addGap(54, 54, 54)
                .addComponent(okbtn)
                .addGap(113, 113, 113))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        titlab1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        titlab1.setForeground(java.awt.Color.blue);
        titlab1.setText("Pedal Powered Washing Machine");

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        titlab2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titlab2.setForeground(new java.awt.Color(255, 51, 51));
        titlab2.setText("Fill the details for calculating Force and Time taken:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("Weight of clothes");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Age Group");

        acb.setEditable(true);
        acb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10-15(children)", "16-20(adol.)", "21-39(young)", "40+(old)" }));

        cal.setForeground(new java.awt.Color(102, 0, 255));
        cal.setText("Calculate");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        ex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ex.setForeground(new java.awt.Color(153, 51, 0));
        ex.setText("Exit");
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });

        lst.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        lst.setForeground(new java.awt.Color(0, 204, 51));
        lst.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Top view", "Front view", "Side view" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lst.setVisibleRowCount(3);
        lst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lst);

        ck.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ck.setForeground(new java.awt.Color(51, 51, 0));
        ck.setText("Checked all the details");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Calculated Details");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "kilo of clothes", "Name", "Time", "Force"
            }
        ));
        jScrollPane5.setViewportView(tbl);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 255));
        jLabel6.setText("Search by kilo clothes");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Searched Details");

        cd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cd.setForeground(new java.awt.Color(255, 0, 51));
        cd.setText("Clear Data");
        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });

        dlb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dlb.setForeground(new java.awt.Color(0, 153, 153));
        dlb.setText("details:");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntfActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("Show Pic");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl.setText("jLabel8");
        scpn.setViewportView(lbl);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Whether to be saved", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        yrb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yrb.setForeground(new java.awt.Color(0, 153, 0));
        yrb.setSelected(true);
        yrb.setText("Yes");
        yrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yrbActionPerformed(evt);
            }
        });

        nrb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nrb.setForeground(new java.awt.Color(153, 0, 153));
        nrb.setText("No");
        nrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(yrb)
                .addGap(28, 28, 28)
                .addComponent(nrb)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yrb)
                    .addComponent(nrb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titlab1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(dlb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titlab2)
                                .addGap(146, 146, 146)
                                .addComponent(cd))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(acb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(wtf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(221, 221, 221)
                                                .addComponent(ex)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(339, 339, 339)
                                        .addComponent(ck)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel5)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scpn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlab1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(scpn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ck)
                        .addGap(18, 18, 18)
                        .addComponent(cal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titlab2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ex)
                            .addComponent(jLabel2)
                            .addComponent(wtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(stf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {
    	 public static void main( String[] args ){//GEN-FIRST:event_calActionPerformed
 String name;double pf,pf2,n1,t1,t2,i,j;
name=ntf.getText();
double wght=Double.parseDouble(wtf.getText());
String txt=(String)acb.getSelectedItem();
 if ((wght<=1) && ck.isSelected()==true){
     pf=104.5+(wght*100);
     n1=(13379/pf);
   if (wght>=.1 && wght<=.3) {
       t1=(2000/n1);
   }else if (wght>.3 && wght<=.6){
       t1=(4000/n1);
       }else{ 
     t1=(6000/n1);
   }
   pf2=Math.round(pf);
  t2=Math.round(t1);
     jTextArea1.setText("You will need"+ ""+pf+"Newtons"+" and "+""+t2+"minutes");
 }}
 else
 {   
     JOptionPane.showMessageDialog("Cloth limit is upto 1kg(please enter in decimal degit and check the detatl box)");
     Message.setText("Cloth limit is upto 1kg(please enter in decimal degit and check the detail box)");
     MsgDialog.setVisible(true);
 }
 String item
// TODO add your handling code here:
    }//GEN-LAST:event_calActionPerformed

    private void ntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntfActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        // TODO adString txt=Message.getText();
String txt1= Message.getText();
        if(txt1.equals("Cloth limit is upto 1kg(please enter in decimal degit)"))
{MsgDialog.dispose();
}
else{
MsgDialog.dispose();
System.exit(0);
        }

    }//GEN-LAST:event_okbtnActionPerformed

    private void lstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstValueChanged
import javax,swing.ImageIcon;
int i=lst.getSelectedIndex();
switch(i){
case 0:lbl.setIcon(new ImageIcon ("C:\\Users\\kumar gaurav\\Documents\\NetBeansProjects\\pedal_powered\\img\\topview.jpg"));
break;
case 1:lbl.setIcon(new ImageIcon ("C:\\Users\\kumar gaurav\\Documents\\NetBeansProjects\\pedal_powered\\img\\frontview.jpg"));
break;
case 2:lbl.setIcon(new ImageIcon ("C:\\Users\\kumar gaurav\\Documents\\NetBeansProjects\\pedal_powered\\img\\sideview.jpg"));
break;// TODO add your handling code here:
    }//GEN-LAST:event_lstValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrbActionPerformed
DefaultTableModel tm=(DefaultTableModel)tbl.getModel();
Object [] oary={pf,t2};
tm.addRow(oary);
try{
String sql="insert into pedalpwd(kilo,name,time,force)values(?,?,?,?)";
pst=conn.prepareStatement(sql);
pst.setString(1,wtf.getText());
pst.setString(2,ntf.getText());
pst.setString(3,t2);
pst.setString(4,pf);
JOptionPane.showMessageDialog(null,"saved");
pst.execute();
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}
Update_table();
}

// TODO add your handling code here:
    }//GEN-LAST:event_yrbActionPerformed

    private void nrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrbActionPerformed
JOptionPane.showMessageDialog(null,"Are you sure of not seeing data in table");        // TODO add your handling code here:
    }//GEN-LAST:event_nrbActionPerformed

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed
DefaultTableModel tm1=(DefaultTableModel)cd.getModel();
int p = JOptionPane.showMessageDialog(null,"Do you want to clear this record");
if (p==0){
String sql="delete from pedalpwd where kilo=?";
 try {
pst=conn.prepareStatement(sql);
pst.setString(1,stf.getText());
pst.execute();
JOptionPane.showMessageDialog(null,"cleared");
}catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}
Update_table();
}
    }//GEN-LAST:event_cdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
String sql="select * from pedalpwd where kilo=?";
pst=conn.prepareStatement(sql);
pst.setString(1,stf.getText());
rs=pst.executeQuery();
if (rs.next()){
String add1=rs.getString("kilo");
dlb.setText(add1);
String add2=rs.getString("name");
dlb.append(add2);
String add3=rs.getString("time");
dlb.append(add3);
String add4=rs.getString("force");
dlb.append(add4);
}catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ppf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ppf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ppf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ppf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ppf1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JDialog MsgDialog;
    private javax.swing.JComboBox acb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cal;
    private javax.swing.JButton cd;
    private javax.swing.JCheckBox ck;
    private javax.swing.JLabel dlb;
    private javax.swing.JButton ex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl;
    private javax.swing.JList lst;
    private javax.swing.JRadioButton nrb;
    private javax.swing.JTextField ntf;
    private javax.swing.JButton okbtn;
    private javax.swing.JScrollPane scpn;
    private javax.swing.JTextField stf;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel titlab1;
    private javax.swing.JLabel titlab2;
    private javax.swing.JTextField wtf;
    private javax.swing.JRadioButton yrb;
    // End of variables declaration//GEN-END:variables
}
